"""Generate CalculiX .inp input files from an FEA job payload."""

from __future__ import annotations

import math


_AXIS_DOF = {"X": 1, "Y": 2, "Z": 3}

_SYMMETRY_LOCKED: dict[str, list[int]] = {
    "YZ": [1],      # normal = X → lock Ux
    "XZ": [2],      # normal = Y → lock Uy
    "XY": [3],      # normal = Z → lock Uz
}


def generate_calculix_input(
    job_name: str,
    mesh_filename: str,
    material: dict,
    constraints: list[dict],
    loads: list[dict],
) -> str:
    """Build a complete CalculiX .inp deck as a string."""
    lines: list[str] = []

    lines.append("*HEADING")
    lines.append(f"{job_name} -- generated by AutoAnsys FEA")
    lines.append("")

    lines.append(f"*INCLUDE, INPUT={mesh_filename}")
    lines.append("")

    # ── Material ──────────────────────────────────────────────────────────
    lines.append("*MATERIAL, NAME=PART_MATERIAL")
    lines.append("*ELASTIC")
    lines.append(f"{material['youngs_modulus']}, {material['poissons_ratio']}")
    lines.append("*DENSITY")
    lines.append(f"{material['density']}")
    lines.append("")
    lines.append("*SOLID SECTION, ELSET=EALL, MATERIAL=PART_MATERIAL")
    lines.append("")

    # ── Boundary conditions ───────────────────────────────────────────────
    lines.append("** --- BOUNDARY CONDITIONS ---")
    for i, bc in enumerate(constraints):
        _write_constraint(lines, bc, i)

    lines.append("")

    # ── Loads ─────────────────────────────────────────────────────────────
    lines.append("** --- LOADS ---")
    for i, load in enumerate(loads):
        _write_load(lines, load, i, material)

    lines.append("")

    # ── Step ──────────────────────────────────────────────────────────────
    lines.append("*STEP")
    lines.append("*STATIC")
    lines.append("")
    lines.append("*NODE PRINT, NSET=NALL")
    lines.append("U")
    lines.append("*EL PRINT, ELSET=EALL")
    lines.append("S")
    lines.append("*NODE FILE")
    lines.append("U")
    lines.append("*EL FILE")
    lines.append("S")
    lines.append("*END STEP")
    lines.append("")

    return "\n".join(lines)


def _nset_name(face_ids: list[str], index: int) -> str:
    if face_ids:
        return face_ids[0].upper().replace(" ", "_")
    return f"BC_{index}"


def _write_constraint(lines: list[str], bc: dict, index: int) -> None:
    ctype = bc["type"]
    face_ids = bc.get("face_ids", [])
    nset = _nset_name(face_ids, index)

    if ctype == "fixed":
        lines.append(f"*BOUNDARY")
        lines.append(f"{nset}, 1, 3, 0.0")

    elif ctype == "pinned":
        lines.append(f"*BOUNDARY")
        lines.append(f"{nset}, 1, 3, 0.0")

    elif ctype == "roller":
        axis = bc.get("axis", "Y")
        dof = _AXIS_DOF.get(axis.upper(), 2)
        lines.append(f"*BOUNDARY")
        lines.append(f"{nset}, {dof}, {dof}, 0.0")

    elif ctype == "symmetry":
        plane = bc.get("plane", "XZ")
        locked_dofs = _SYMMETRY_LOCKED.get(plane.upper(), [2])
        lines.append(f"*BOUNDARY")
        for dof in locked_dofs:
            lines.append(f"{nset}, {dof}, {dof}, 0.0")

    elif ctype == "displacement":
        disp = bc.get("displacement", {})
        lines.append(f"*BOUNDARY")
        for axis_label, dof in _AXIS_DOF.items():
            val = disp.get(axis_label.lower())
            if val is not None:
                lines.append(f"{nset}, {dof}, {dof}, {val}")


def _write_load(lines: list[str], load: dict, index: int, material: dict) -> None:
    ltype = load["type"]
    face_ids = load.get("face_ids") or []
    nset = _nset_name(face_ids, index) if face_ids else f"LOAD_{index}"

    if ltype == "force":
        direction = load.get("direction", {})
        magnitude = load.get("magnitude", 0)
        dx, dy, dz = direction.get("x", 0), direction.get("y", 0), direction.get("z", 0)
        norm = math.sqrt(dx * dx + dy * dy + dz * dz)
        if norm > 0:
            dx, dy, dz = dx / norm, dy / norm, dz / norm
        for axis_label, dof in _AXIS_DOF.items():
            comp = {"X": dx, "Y": dy, "Z": dz}[axis_label] * magnitude
            if abs(comp) > 1e-12:
                lines.append(f"*CLOAD")
                lines.append(f"{nset}, {dof}, {comp}")

    elif ltype == "pressure":
        magnitude = load.get("magnitude", 0)
        lines.append(f"*DLOAD")
        lines.append(f"{nset}, P, {magnitude}")

    elif ltype == "gravity":
        direction = load.get("direction", {})
        g = load.get("g", 9.81)
        dx, dy, dz = direction.get("x", 0), direction.get("y", -1), direction.get("z", 0)
        lines.append(f"*DLOAD")
        lines.append(f"EALL, GRAV, {g}, {dx}, {dy}, {dz}")

    elif ltype == "displacement":
        disp = load.get("displacement", {})
        lines.append(f"*BOUNDARY")
        for axis_label, dof in _AXIS_DOF.items():
            val = disp.get(axis_label.lower())
            if val is not None:
                lines.append(f"{nset}, {dof}, {dof}, {val}")
